global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.

rule_files:
- "rules.yml"

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['127.0.0.1:9090']

- job_name: 'spring-actuator'
  metrics_path: '/actuator/prometheus'
  static_configs:
  - targets: ['HOST:8080']